# Generated by Django 4.1.7 on 2023-04-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productimage",
            name="name",
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.ImageField(default="test.jpg", upload_to=None),
        ),
    ]
