# Generated by Django 4.1.7 on 2023-04-06 04:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productline",
            options={"verbose_name_plural": "Product Lines"},
        ),
        migrations.AddField(
            model_name="producttype",
            name="attributes",
            field=models.ManyToManyField(
                related_name="product_type_attributes",
                through="product.ProductTypeAttribute",
                to="product.attribute",
            ),
        ),
    ]
