# Generated by Django 4.1.7 on 2023-04-01 16:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price",
        ),
    ]
